import { RepaymentStrategy, GenerateScheduleInput, GeneratedInstallment } from "../repayment.types";

/**
 * STRUCTURED / CUSTOM: per SRS, these schedules are manually defined by
 * the admin (e.g. "Month 1-2 interest-only, Month 3 principal, Month 4
 * balloon payment") rather than auto-generated by a formula. This engine
 * does not auto-generate them — it throws, signaling the caller must
 * supply installments directly via manual entry instead of this generator.
 */
export const structuredStrategy: RepaymentStrategy = {
  generate(_input: GenerateScheduleInput): GeneratedInstallment[] {
    throw new Error(
      "STRUCTURED/CUSTOM schedules must be entered manually; auto-generation is not supported."
    );
  },
};